version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: bun-postgres
    restart: always
    environment:
      POSTGRES_USER: bun_user
      POSTGRES_PASSWORD: bun_password
      POSTGRES_DB: bun_bank
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
