version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: bun-postgres
    restart: always
    environment:
      POSTGRES_USER: bun_user
      POSTGRES_PASSWORD: bun_password
      POSTGRES_DB: bun_bank
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

# JAEGER (Monitoring Dashboard)
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: bun-jaeger
    restart: always
    # Environment ini penting biar dia mau nerima data dari luar
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686" # Port Website (UI) - Kita buka ini di browser
      - "4318:4318"   # Port Penerima Data (HTTP) - Bun kirim ke sini
      - "4317:4317"   # Port Penerima Data (gRPC)

volumes:
  pgdata:
